// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFKn-GJiuKCvcVl1J1R97O4GpZSHdYXKg',
    appId: '1:495495909284:web:daae843221eddf2fef7b31',
    messagingSenderId: '495495909284',
    projectId: 'fuelwise-184d7',
    authDomain: 'fuelwise-184d7.firebaseapp.com',
    storageBucket: 'fuelwise-184d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKKiVCrFfDqEObZy_RdMLE-H8RUKN5Eow',
    appId: '1:495495909284:android:cadd8a5b9f2caaadef7b31',
    messagingSenderId: '495495909284',
    projectId: 'fuelwise-184d7',
    storageBucket: 'fuelwise-184d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Su24A3Syu7hMvBcQOO4uw_T3zIJtbaY',
    appId: '1:495495909284:ios:0979c94f27dd4385ef7b31',
    messagingSenderId: '495495909284',
    projectId: 'fuelwise-184d7',
    storageBucket: 'fuelwise-184d7.appspot.com',
    iosClientId: '495495909284-pmvnhjehq8064b5sjsgsle0958u0latj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fuelwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Su24A3Syu7hMvBcQOO4uw_T3zIJtbaY',
    appId: '1:495495909284:ios:0979c94f27dd4385ef7b31',
    messagingSenderId: '495495909284',
    projectId: 'fuelwise-184d7',
    storageBucket: 'fuelwise-184d7.appspot.com',
    iosClientId: '495495909284-pmvnhjehq8064b5sjsgsle0958u0latj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fuelwise',
  );
}
